# Generated by Django 4.2.17 on 2025-02-23 23:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_plano_delete_pacoteplano_alter_team_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plano',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.RemoveField(
            model_name='plano',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='cor_destaque',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='data_termino',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='preco_padrao',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='preco_promocional',
        ),
        migrations.RemoveField(
            model_name='plano',
            name='tipo',
        ),
        migrations.AddField(
            model_name='plano',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Mensal'), ('quarterly', 'Trimestral'), ('semiannual', 'Semestral'), ('annual', 'Anual')], default='monthly', max_length=20, verbose_name='Vigência'),
        ),
        migrations.AddField(
            model_name='plano',
            name='billing_cycle_text_color',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor Texto Vigência'),
        ),
        migrations.AddField(
            model_name='plano',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='plano',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='plano',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Padrão'),
        ),
        migrations.AddField(
            model_name='plano',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='planos/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='plano',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='plano',
            name='label_background_color',
            field=models.CharField(default='#192639', max_length=7, verbose_name='Cor Fundo Etiqueta'),
        ),
        migrations.AddField(
            model_name='plano',
            name='label_text_color',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor Texto Etiqueta'),
        ),
        migrations.AddField(
            model_name='plano',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='plano',
            name='package_type',
            field=models.CharField(choices=[('basic', 'Básico'), ('premium', 'Premium'), ('pro', 'Profissional')], default='basic', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='plano',
            name='plan',
            field=models.CharField(default='', max_length=100, verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='plano',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
        migrations.AddField(
            model_name='plano',
            name='show_to',
            field=models.CharField(choices=[('all', 'Todos'), ('new', 'Novos Usuários'), ('existing', 'Usuários Existentes')], default='all', max_length=20, verbose_name='Exibir Para'),
        ),
        migrations.AddField(
            model_name='plano',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='plano',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterModelTable(
            name='plano',
            table='planos',
        ),
    ]
