# Generated by Django 4.2.17 on 2025-02-23 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_pacoteplano'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('mensal', 'Mensal'), ('semestral', 'Semestral'), ('anual', 'Anual')], max_length=20)),
                ('preco_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('cor_destaque', models.CharField(default='#192639', max_length=7)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.DeleteModel(
            name='PacotePlano',
        ),
        migrations.AlterField(
            model_name='team',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='administrativo.country'),
            preserve_default=False,
        ),
    ]
