# Generated by Django 4.2.17 on 2025-02-24 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0006_alter_plano_options_remove_plano_ativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='is_active',
            new_name='enabled',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='duration_days',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='price',
        ),
        migrations.AddField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='color_background_label',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='color_text_billing_cycle',
            field=models.CharField(default='#192639', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='color_text_label',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/'),
        ),
        migrations.AddField(
            model_name='plan',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='package_type',
            field=models.CharField(choices=[('Padrão', 'Padrão'), ('Promocional', 'Promocional')], default='Padrão', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='plan',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='show_to',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Comum', 'Comum'), ('Craque', 'Craque')], default='Todos', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
