# Generated by Django 4.2.17 on 2025-02-24 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0009_plan_promotional_price_validity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='futcoinpackage',
            options={'ordering': ['name'], 'verbose_name': 'Pacote Futcoin', 'verbose_name_plural': 'Pacotes Futcoins'},
        ),
        migrations.RemoveField(
            model_name='futcoinpackage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='futcoinpackage',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='futcoinpackage',
            name='price',
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='bonus',
            field=models.IntegerField(default=0, verbose_name='Bônus'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='color_background_label',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor de Fundo da Etiqueta'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='color_text_label',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor do Texto da Etiqueta'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='content',
            field=models.IntegerField(default=0, verbose_name='Conteúdo'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='full_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Padrão'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='futcoins/packages/', verbose_name='Imagem'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='package_type',
            field=models.CharField(choices=[('padrao', 'Padrão'), ('promocional', 'Promocional')], default='padrao', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='show_to',
            field=models.CharField(choices=[('todos', 'Todos'), ('comum', 'Comum'), ('craque', 'Craque')], default='todos', max_length=20, verbose_name='Exibir Para'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='futcoinpackage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
