# Generated by Django 4.2.17 on 2025-02-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0010_alter_futcoinpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='futcoinpackage',
            name='android_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (Android)'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='gateway_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (Gateway)'),
        ),
        migrations.AddField(
            model_name='futcoinpackage',
            name='ios_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (iOS)'),
        ),
    ]
