# Generated by Django 4.2.17 on 2025-02-24 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0011_futcoinpackage_android_product_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='futligas/custom/', verbose_name='Imagem')),
                ('privacy', models.CharField(choices=[('public', 'Pública'), ('private', 'Privada')], default='public', max_length=20, verbose_name='Privacidade')),
                ('players', models.IntegerField(verbose_name='Quantidade de Participantes')),
                ('premium_players', models.IntegerField(verbose_name='Quantidade de Craques')),
                ('owner_premium', models.BooleanField(default=False, verbose_name='Dono Craque')),
                ('league_link', models.URLField(blank=True, null=True, verbose_name='Link do Grupo')),
                ('level', models.IntegerField(choices=[(1, 'Nível 1'), (2, 'Nível 2'), (3, 'Nível 3')], default=1, verbose_name='Nível')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Futliga Personalizada',
                'verbose_name_plural': 'Futligas Personalizadas',
                'db_table': 'custom_leagues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StandardLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='futligas/standard/', verbose_name='Imagem')),
                ('award_frequency', models.CharField(choices=[('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='Frequência de Premiação')),
                ('weekday', models.IntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='Dia da Semana')),
                ('players', models.IntegerField(verbose_name='Quantidade de Participantes')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('plans', models.ManyToManyField(to='administrativo.plan', verbose_name='Planos')),
            ],
            options={
                'verbose_name': 'Futliga Padrão',
                'verbose_name_plural': 'Futligas Padrão',
                'db_table': 'standard_leagues',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeagueInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitations', models.IntegerField(default=0, verbose_name='Quantidade de Convites')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='league_invitations', to='administrativo.user', verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Convite de Futliga',
                'verbose_name_plural': 'Convites de Futliga',
                'db_table': 'league_invitations',
            },
        ),
        migrations.CreateModel(
            name='StandardLeaguePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Posição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='futligas/prizes/', verbose_name='Imagem')),
                ('prize', models.CharField(max_length=255, verbose_name='Prêmio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='administrativo.standardleague', verbose_name='Futliga')),
            ],
            options={
                'verbose_name': 'Prêmio de Futliga Padrão',
                'verbose_name_plural': 'Prêmios de Futliga Padrão',
                'db_table': 'standard_league_prizes',
                'ordering': ['position'],
                'unique_together': {('league', 'position')},
            },
        ),
        migrations.CreateModel(
            name='CustomLeaguePrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(verbose_name='Posição')),
                ('image', models.ImageField(blank=True, null=True, upload_to='futligas/prizes/', verbose_name='Imagem')),
                ('prize', models.CharField(max_length=255, verbose_name='Prêmio')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes', to='administrativo.customleague', verbose_name='Futliga')),
            ],
            options={
                'verbose_name': 'Prêmio de Futliga Personalizada',
                'verbose_name_plural': 'Prêmios de Futliga Personalizada',
                'db_table': 'custom_league_prizes',
                'ordering': ['position'],
                'unique_together': {('league', 'position')},
            },
        ),
    ]
