# Generated by Django 4.2.17 on 2025-02-24 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_customleague_standardleague_leagueinvitation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLeagueLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('image', models.ImageField(blank=True, null=True, upload_to='futligas/levels/', verbose_name='Imagem')),
                ('players', models.IntegerField(verbose_name='Quantidade de Participantes')),
                ('premium_players', models.IntegerField(verbose_name='Quantidade de Craques')),
                ('owner_premium', models.BooleanField(default=False, verbose_name='Dono Craque')),
                ('order', models.IntegerField(default=0, verbose_name='Ordem')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Nível de Futliga',
                'verbose_name_plural': 'Níveis de Futliga',
                'db_table': 'custom_league_levels',
                'ordering': ['order'],
            },
        ),
    ]
