# Generated by Django 4.2.17 on 2025-02-24 16:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0013_customleaguelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensagem')),
                ('notification_type', models.CharField(choices=[('generic', 'Geral'), ('package_plan', 'Pacote Plano'), ('package_coins', 'Pacote Futcoin')], default='generic', max_length=20, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('not_sent', 'Não Enviado')], default='pending', max_length=20, verbose_name='Status')),
                ('immediate_send', models.BooleanField(default=True, verbose_name='Envio Imediato')),
                ('send_at', models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de Atualização')),
                ('package_coins', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='administrativo.futcoinpackage', verbose_name='Pacote Futcoin')),
                ('package_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='administrativo.plan', verbose_name='Pacote Plano')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255, verbose_name='Nome')),
                ('value', models.PositiveIntegerField(default=0, verbose_name='Valor')),
                ('description', models.TextField(default='', verbose_name='Descrição')),
                ('tab', models.CharField(default='Geral', max_length=50, verbose_name='Aba')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parâmetro',
                'verbose_name_plural': 'Parâmetros',
                'db_table': 'parameters',
                'ordering': ['tab', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('notify_changes', models.BooleanField(default=False, verbose_name='Notificar Mudanças')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Termo',
                'verbose_name_plural': 'Termos',
                'db_table': 'terms',
            },
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Parameter',
        ),
        migrations.DeleteModel(
            name='Term',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
