# Generated by Django 4.2.17 on 2025-02-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_alter_administrator_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrator',
            options={'verbose_name': 'Administrador', 'verbose_name_plural': 'Administradores'},
        ),
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['-created_at'], 'verbose_name': 'Campeonato', 'verbose_name_plural': 'Campeonatos'},
        ),
        migrations.AlterModelOptions(
            name='championshipmatch',
            options={'ordering': ['match_date'], 'verbose_name': 'Partida do Campeonato', 'verbose_name_plural': 'Partidas do Campeonato'},
        ),
        migrations.AlterModelOptions(
            name='championshipround',
            options={'ordering': ['number'], 'verbose_name': 'Rodada do Campeonato', 'verbose_name_plural': 'Rodadas do Campeonato'},
        ),
        migrations.AlterModelOptions(
            name='championshipstage',
            options={'ordering': ['order'], 'verbose_name': 'Fase do Campeonato', 'verbose_name_plural': 'Fases do Campeonato'},
        ),
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Continente', 'verbose_name_plural': 'Continentes'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='customleague',
            options={'ordering': ['name'], 'verbose_name': 'Futliga Personalizada', 'verbose_name_plural': 'Futligas Personalizadas'},
        ),
        migrations.AlterModelOptions(
            name='customleaguelevel',
            options={'ordering': ['order'], 'verbose_name': 'Nível de Futliga', 'verbose_name_plural': 'Níveis de Futliga'},
        ),
        migrations.AlterModelOptions(
            name='customleagueprize',
            options={'ordering': ['position'], 'verbose_name': 'Prêmio de Futliga Personalizada', 'verbose_name_plural': 'Prêmios de Futliga Personalizada'},
        ),
        migrations.AlterModelOptions(
            name='futcoinpackage',
            options={'ordering': ['name'], 'verbose_name': 'Pacote Futcoin', 'verbose_name_plural': 'Pacotes Futcoins'},
        ),
        migrations.AlterModelOptions(
            name='leagueinvitation',
            options={'verbose_name': 'Convite de Futliga', 'verbose_name_plural': 'Convites de Futliga'},
        ),
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelOptions(
            name='parameters',
            options={'verbose_name': 'Parâmetro', 'verbose_name_plural': 'Parâmetros'},
        ),
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plan', 'verbose_name_plural': 'Plans'},
        ),
        migrations.AlterModelOptions(
            name='prediction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Palpite', 'verbose_name_plural': 'Palpites'},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['type'], 'verbose_name': 'Âmbito', 'verbose_name_plural': 'Âmbitos'},
        ),
        migrations.AlterModelOptions(
            name='scopelevel',
            options={'verbose_name': 'Nível de Âmbito', 'verbose_name_plural': 'Níveis de Âmbito'},
        ),
        migrations.AlterModelOptions(
            name='standardleague',
            options={'ordering': ['name'], 'verbose_name': 'Futliga Padrão', 'verbose_name_plural': 'Futligas Padrão'},
        ),
        migrations.AlterModelOptions(
            name='standardleagueprize',
            options={'ordering': ['position'], 'verbose_name': 'Prêmio de Futliga Padrão', 'verbose_name_plural': 'Prêmios de Futliga Padrão'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name'], 'verbose_name': 'Time', 'verbose_name_plural': 'Times'},
        ),
        migrations.AlterModelOptions(
            name='template',
            options={'verbose_name': 'Template', 'verbose_name_plural': 'Templates'},
        ),
        migrations.AlterModelOptions(
            name='templatestage',
            options={'ordering': ['order'], 'verbose_name': 'Fase do Template', 'verbose_name_plural': 'Fases do Template'},
        ),
        migrations.AlterModelOptions(
            name='terms',
            options={'verbose_name': 'Termo', 'verbose_name_plural': 'Termos'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='immediate_send',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='package_coins',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='package_plan',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='description',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='name',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='tab',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='value',
        ),
        migrations.AddField(
            model_name='notifications',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='administrativo.futcoinpackage', verbose_name='Pacote'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='ace_leagues_participation',
            field=models.IntegerField(default=0, help_text='Limite de participação em Futligas para usuários premium', verbose_name='Participação em Futligas (Craque)'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='consecutive_days_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos por dias consecutivos de login', verbose_name='Futcoins por Dias Seguidos'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='daily_videos_limit',
            field=models.IntegerField(default=0, help_text='Quantidade máxima de vídeos que podem ser assistidos por dia', verbose_name='Limite de Vídeos Diários'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='following_tiktok_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos por seguir no TikTok', verbose_name='Futcoins por Seguir TikTok'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='hit_prediction_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos por acertar palpite', verbose_name='Futcoins por Acerto'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='login_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos no login', verbose_name='Futcoins de Login'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='login_day',
            field=models.IntegerField(default=0, help_text='Valor em Futcoins para recompensa diária de login', verbose_name='Dia de Login'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='login_image',
            field=models.ImageField(blank=True, null=True, upload_to='parameters/', verbose_name='Imagem de Login'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='premium_upgrade_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos por fazer upgrade para conta premium', verbose_name='Futcoins por Upgrade Premium'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='standard_leagues_participation',
            field=models.IntegerField(default=0, help_text='Limite de participação em Futligas para usuários comuns', verbose_name='Participação em Futligas (Comum)'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='watch_video_coins',
            field=models.IntegerField(default=0, help_text='Quantidade de Futcoins recebidos por assistir vídeo', verbose_name='Futcoins por Vídeo'),
        ),
        migrations.AlterUniqueTogether(
            name='championship',
            unique_together={('name', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='championshipround',
            unique_together={('championship', 'stage', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='championshipstage',
            unique_together={('championship', 'order')},
        ),
        migrations.AlterUniqueTogether(
            name='customleagueprize',
            unique_together={('league', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='prediction',
            unique_together={('user', 'match')},
        ),
        migrations.AlterUniqueTogether(
            name='scopelevel',
            unique_together={('scope', 'type', 'level')},
        ),
        migrations.AlterUniqueTogether(
            name='standardleagueprize',
            unique_together={('league', 'position')},
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('name', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='templatestage',
            unique_together={('template', 'order')},
        ),
        migrations.AlterModelTable(
            name='administrator',
            table='administrators',
        ),
        migrations.AlterModelTable(
            name='championship',
            table='championships',
        ),
        migrations.AlterModelTable(
            name='championshipmatch',
            table='championship_matches',
        ),
        migrations.AlterModelTable(
            name='championshipround',
            table='championship_rounds',
        ),
        migrations.AlterModelTable(
            name='championshipstage',
            table='championship_stages',
        ),
        migrations.AlterModelTable(
            name='classicleague',
            table='classic_leagues',
        ),
        migrations.AlterModelTable(
            name='customleague',
            table='custom_leagues',
        ),
        migrations.AlterModelTable(
            name='customleaguelevel',
            table='custom_league_levels',
        ),
        migrations.AlterModelTable(
            name='customleagueprize',
            table='custom_league_prizes',
        ),
        migrations.AlterModelTable(
            name='futcoinpackage',
            table='futcoin_packages',
        ),
        migrations.AlterModelTable(
            name='leagueinvitation',
            table='league_invitations',
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
        migrations.AlterModelTable(
            name='parameters',
            table='parameters',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plans',
        ),
        migrations.AlterModelTable(
            name='player',
            table='players',
        ),
        migrations.AlterModelTable(
            name='prediction',
            table='predictions',
        ),
        migrations.AlterModelTable(
            name='scope',
            table='scopes',
        ),
        migrations.AlterModelTable(
            name='scopelevel',
            table='scope_levels',
        ),
        migrations.AlterModelTable(
            name='standardleague',
            table='standard_leagues',
        ),
        migrations.AlterModelTable(
            name='standardleagueprize',
            table='standard_league_prizes',
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
        migrations.AlterModelTable(
            name='template',
            table='templates',
        ),
        migrations.AlterModelTable(
            name='templatestage',
            table='template_stages',
        ),
        migrations.AlterModelTable(
            name='terms',
            table='terms',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
