# Generated by Django 4.2.17 on 2025-02-24 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_parameters'),
        ('administrativo', '0016_alter_administrator_options_and_more'),
    ]

    operations = [
    ]
