# Generated by Django 4.2.17 on 2025-02-25 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='login_coins',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='login_day',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='login_image',
        ),
        migrations.AddField(
            model_name='parameters',
            name='day1_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 1'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day2_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 2'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day3_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 3'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day4_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 4'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day5_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 5'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day6_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 6'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='day7_coins',
            field=models.IntegerField(default=0, verbose_name='Dia 7'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='reward_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário Premiação'),
        ),
    ]
