# Generated by Django 4.2.17 on 2025-02-18 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'Âmbito', 'verbose_name_plural': 'Âmbitos'},
        ),
        migrations.RemoveField(
            model_name='scope',
            name='description',
        ),
        migrations.AddField(
            model_name='scope',
            name='boost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scope',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='scope',
            name='insurance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scope',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scope',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scope',
            name='leverage',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scope',
            name='point',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scope',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='scope',
            name='type',
            field=models.CharField(choices=[('estadual', 'Estadual'), ('nacional', 'Nacional'), ('continental', 'Continental'), ('mundial', 'Mundial')], default='estadual', max_length=20),
        ),
        migrations.AddField(
            model_name='scope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
