# Generated by Django 4.2.17 on 2025-02-25 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_remove_parameters_login_coins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Chave de API (Tiny)'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contato'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='kwai',
            field=models.URLField(blank=True, null=True, verbose_name='Kwai'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='tiktok',
            field=models.URLField(blank=True, null=True, verbose_name='TikTok'),
        ),
    ]
