# Generated by Django 4.2.17 on 2025-02-18 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0002_alter_scope_options_remove_scope_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scope',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='level',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='leverage',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='point',
        ),
        migrations.RemoveField(
            model_name='scope',
            name='price',
        ),
        migrations.AddField(
            model_name='scope',
            name='futcoins',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ScopeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('leverage', 'Alavancagem'), ('insurance', 'Seguro')], max_length=20)),
                ('level', models.IntegerField()),
                ('points', models.IntegerField(default=0)),
                ('futcoins', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='administrativo.scope')),
            ],
            options={
                'verbose_name': 'Nível de Âmbito',
                'verbose_name_plural': 'Níveis de Âmbito',
                'db_table': 'scope_levels',
                'unique_together': {('scope', 'type', 'level')},
            },
        ),
    ]
