# Generated by Django 4.2.17 on 2025-02-18 16:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_remove_scope_insurance_remove_scope_level_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='continent',
            options={'ordering': ['name'], 'verbose_name': 'Continente', 'verbose_name_plural': 'Continentes'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.AlterModelOptions(
            name='state',
            options={'ordering': ['name'], 'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.RenameField(
            model_name='continent',
            old_name='data_criacao',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='continent',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='country',
            name='code',
        ),
        migrations.RemoveField(
            model_name='country',
            name='is_active',
        ),
        migrations.AddField(
            model_name='continent',
            name='name',
            field=models.CharField(default='Temporario', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='country',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='state',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='country',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.continent'),
        ),
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administrativo.country'),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='state',
            unique_together={('name', 'country')},
        ),
        migrations.AlterModelTable(
            name='country',
            table=None,
        ),
        migrations.AlterModelTable(
            name='state',
            table=None,
        ),
        migrations.RemoveField(
            model_name='state',
            name='code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='is_active',
        ),
    ]
