# Generated by Django 4.2.17 on 2025-02-23 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0003_alter_team_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PacotePlano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('plano', models.CharField(max_length=50)),
                ('vigencia', models.CharField(choices=[('Mensal', 'Mensal'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='planos/')),
                ('ativo', models.BooleanField(default=True)),
                ('tipo', models.CharField(choices=[('Padrão', 'Padrão'), ('Promocional', 'Promocional')], max_length=20)),
                ('etiqueta', models.CharField(blank=True, max_length=50, null=True)),
                ('cor_texto_etiqueta', models.CharField(default='#000000', max_length=7)),
                ('cor_fundo_etiqueta', models.CharField(default='#FFFFFF', max_length=7)),
                ('preco_padrao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_promocional', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cor_texto_vigencia', models.CharField(default='#192639', max_length=7)),
                ('exibir_para', models.CharField(choices=[('Todos', 'Todos'), ('Comum', 'Comum'), ('Craque', 'Craque')], max_length=20)),
                ('data_inicio', models.DateTimeField(blank=True, null=True)),
                ('data_termino', models.DateTimeField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pacote Plano',
                'verbose_name_plural': 'Pacotes Planos',
                'db_table': 'pacotes_planos',
            },
        ),
    ]
