# Generated by Django 4.2.17 on 2025-02-18 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0004_alter_continent_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='championship',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ['type'], 'verbose_name': 'Âmbito', 'verbose_name_plural': 'Âmbitos'},
        ),
        migrations.AddField(
            model_name='championship',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='championships', to='administrativo.country'),
        ),
    ]
