# Generated by Django 4.2.17 on 2025-02-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0007_alter_notifications_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parameters',
            name='season_award_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dia da Premiação por Temporada'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='season_award_month',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mês da Premiação por Temporada'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='season_award_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Premiação por Temporada'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='weekly_award_day',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Dia da Premiação Semanal'),
        ),
        migrations.AddField(
            model_name='parameters',
            name='weekly_award_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Horário da Premiação Semanal'),
        ),
    ]
