# Generated by Django 4.2.17 on 2025-02-26 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0008_parameters_season_award_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicleague',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
