# Generated by Django 4.2.17 on 2025-02-27 21:25

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('administrativo', '0011_add_auth_fields_to_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificação', 'verbose_name_plural': 'Notificações'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='notifications',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.plan', verbose_name='Plano'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='administrativo_users', related_query_name='administrativo_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='administrativo_users', related_query_name='administrativo_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='error_message',
            field=models.TextField(blank=True, null=True, verbose_name='Mensagem de Erro'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.TextField(verbose_name='Mensagem'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='notification_type',
            field=models.CharField(choices=[('generic', 'Geral'), ('package_coins', 'Pacote Futcoins'), ('package_plan', 'Pacote Plano')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administrativo.futcoinpackage', verbose_name='Pacote'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='send_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Envio'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('not_sent', 'Não Enviado')], default='pending', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
        migrations.AlterModelTable(
            name='notifications',
            table='notifications',
        ),
    ]
