# Generated by Django 4.2.17 on 2025-02-28 01:19

import administrativo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0012_alter_notifications_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customleague',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=administrativo.models.custom_league_image_path, verbose_name='Imagem'),
        ),
    ]
