# Generated by Django 4.2.17 on 2025-02-28 02:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0014_add_futliga_jogador_parameters'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameters',
            name='key',
        ),
        migrations.RemoveField(
            model_name='parameters',
            name='value',
        ),
        migrations.CreateModel(
            name='CustomLeaguePrizeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Valor')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prize_values', to='administrativo.customleaguelevel', verbose_name='Nível')),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='administrativo.customleagueprize', verbose_name='Prêmio')),
            ],
            options={
                'verbose_name': 'Valor de Prêmio por Nível',
                'verbose_name_plural': 'Valores de Prêmios por Nível',
                'db_table': 'custom_league_prize_values',
                'unique_together': {('prize', 'level')},
            },
        ),
    ]
