# Generated by Django 4.2.17 on 2025-03-01 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0015_remove_parameters_key_remove_parameters_value_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plano', 'verbose_name_plural': 'Planos'},
        ),
        migrations.AddField(
            model_name='plan',
            name='gateway_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (Gateway)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='android_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (Android)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='apple_product_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Produto (Apple)'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='billing_cycle',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=20, verbose_name='Ciclo de Cobrança'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_background_label',
            field=models.CharField(default='#CC000C', max_length=7, verbose_name='Cor de Fundo da Etiqueta'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_text_billing_cycle',
            field=models.CharField(default='#192639', max_length=7, verbose_name='Cor do Texto do Ciclo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='color_text_label',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor do Texto da Etiqueta'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='full_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Padrão'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plans/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='label',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etiqueta'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='package_type',
            field=models.CharField(choices=[('Padrão', 'Padrão'), ('Promocional', 'Promocional')], max_length=20, verbose_name='Tipo do Pacote'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan',
            field=models.CharField(max_length=50, verbose_name='Plano'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='promotional_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='promotional_price_validity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Validade do Preço Promocional'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='show_to',
            field=models.CharField(choices=[('Todos', 'Todos'), ('Comum', 'Comum'), ('Craque', 'Craque')], default='Todos', max_length=20, verbose_name='Exibir Para'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
