# Generated by Django 4.2.17 on 2025-03-01 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0016_alter_plan_options_plan_gateway_product_code_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE `scope_levels` (
              `id` bigint NOT NULL AUTO_INCREMENT,
              `type` varchar(20) NOT NULL,
              `level` integer NOT NULL,
              `points` integer NOT NULL,
              `futcoins` integer NOT NULL,
              `is_active` bool NOT NULL,
              `created_at` datetime(6) NOT NULL,
              `updated_at` datetime(6) NOT NULL,
              `scope_id` bigint NOT NULL,
              PRIMARY KEY (`id`),
              UNIQUE KEY `scope_levels_scope_id_type_level_uniq` (`scope_id`, `type`, `level`),
              CONSTRAINT `scope_levels_scope_id_fk_scopes_id` FOREIGN KEY (`scope_id`) REFERENCES `scopes` (`id`) ON DELETE CASCADE
            ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
            """
        ),
    ]
