# Generated by Django 4.2.17 on 2025-03-22 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0025_add_fields_to_plan'),
    ]

    operations = [
        # Os campos já existem no banco de dados (adicionados pela migração 0023)
        # Mantendo a migração vazia apenas para registro
    ]
